version: '3.5'
networks:
    app-tier:
        driver: bridge
        name: app-tier

services:
    mysql:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        build:
            context: ./mysql
        container_name: server_mysql_1
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'
        hostname: mysql
        networks:
            - app-tier
        volumes:
            - mysql-datavolume:/var/lib/mysql
#            - ./datavolume:/var/lib/mysql
        # volumes:
        #   - type: bind
        #     source: ./datavolume
        #     target: /var/lib/mysql            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: rootpwd
        networks:
            - app-tier

    # adminer:
    #     image: adminer
    #     restart: always
    #     networks:
    #         - app-tier


volumes:
  mysql-datavolume:
